services:
  worker:
    image: dairoot/chatgpt-mirror:latest
    volumes:
      - chatgpt_data:/app/worker/.wrangler

    env_file:
      - .env

    ports:
      - "50001:50001"

    restart: always
    depends_on:
      - warp

    environment:
      - SOCKS5_PROXY=socks5://warp:1080

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - "1080:1080"
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp

volumes:
  chatgpt_data:
